---

# Copyright 2021 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set specific Facts for later use in Cluster Deployment
  ansible.builtin.set_fact:
    _pre_template_cluster: "{{ lookup('file', init__cluster_definition_file ) | from_yaml }}"
    preload_parcels: "{{ download_mirror_file_list | default([]) }}"
    custom_repo_rehost_files: "{{ download_mirror_file_list | default([]) }}"
  delegate_to: "{{ __play_host }}"
  delegate_facts: true
  loop: "{{ groups.all }}"
  loop_control:
    loop_var: __play_host
    label: __play_host

- name: Set Sensitive Facts with no-log for later use in Cluster Deployment
  ansible.builtin.set_fact:
    cloudera_manager_admin_password: "{{ globals.admin_password }}"
    cloudera_manager_license_file: "{{ globals.cloudera_license_file | default(omit) }}"
  delegate_to: "{{ __play_host }}"
  delegate_facts: true
  no_log: true
  loop: "{{ groups.all }}"
  loop_control:
    loop_var: __play_host
    label: __play_host

- name: Include Definition Vars to allow overrides to propagate to Cluster Deployment
  ansible.builtin.include_vars:
    file: "{{ init__user_definition_file }}"
  delegate_to: "{{ __play_host }}"
  delegate_facts: true
  loop: "{{ groups.all }}"
  loop_control:
    loop_var: __play_host
    label : __play_host

- name: Include Cluster Definition override
  ansible.builtin.include_vars:
    file: "{{ init__cluster_definition_file }}"
  delegate_to: "{{ __play_host }}"
  delegate_facts: true
  loop: "{{ groups.all }}"
  loop_control:
    loop_var: __play_host
    label : __play_host